"""
Django settings for money_collect project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import gevent.monkey

gevent.monkey.patch_all()  # ⚠️ Должно быть первым! Патчит все стандартные библиотеки.
import os
from pathlib import Path

from decouple import (
    config as conf,
    Config,
    RepositoryEnv,
)  # импортируем модуль для работы с переменными окружения

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n=kzx^i38odv4$y&ysu8c2qirkg@bg0^9i@u1%^ku&7@4rjw%$"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # Регистрируемые приложения
    "api",
    "money_collect",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "debug_toolbar",                #   для отладки, для продакшена закомментировать
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "django_filters",
    "django_extensions",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Поле для CORS должно быть первым
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "money_collect.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "money_collect.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "moneycollect",
        "USER": "postgres",
        "PASSWORD": "postgres",
        # "HOST": "localhost",
        # "HOST": "db",                           # Имя контейнера с БД db, использовать вместо localhost при развертывании в Docker
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"
# LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Настройки для REST_FRAMEWORK
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://localhost:8000",
#     "http://127.0.0.1:8000",
# ]
CORS_ALLOW_ALL_ORIGINS = True

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
        }
    },
    "USE_SESSION_AUTH": False,
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Настройки для CELERY
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# НАСТРОЙКИ ДЛЯ РАЗРАБОТКИ. НЕ ИСПОЛЬЗУЮТСЯ В РЕЖИМЕ ПРОДАКШН

if DEBUG:
    # Добавляем константу для DjDT, чтобы он понимал - запросы с каких IP адресов надо обрабатывать
    INTERNAL_IPS = [
        "127.0.0.1",
    ]
    # Добавляем прослойку для DjDT
# if DEBUG:
#     MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware",)  # Должен быть последним, для продакшена не используется

# настройки почтового сервера
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Для отправки уведомления в консоль при отладке в разработке
# DEFAULT_FROM_EMAIL = 'no-reply@example.com'   # Для отправки уведомления в консоль
# if DATABASES['HOST'] == 'localhost':
#     config = Config(RepositoryEnv(
#         r'C:/Users/EvgenyMINI_S/PythonProjects/DjangoMoneyCollect/.env.dev'
#         )
#     )
# else: pass

# Настройки почтового list.ru сервера для отправки уведомлений
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.list.ru"  # SMTP сервер list.ru
EMAIL_PORT = 587  # Порт для подключения
EMAIL_USE_TLS = True  # Использование TLS шифрования
EMAIL_USE_SSL = False  # SSL не используется, так как порт 587 работает с TLS
# Если проект развернут локально
if DATABASES["default"]["HOST"] == "localhost":
    config = Config(
        RepositoryEnv(
            r"C:/Users/EvgenyMINI_S/PythonProjects/DjangoMoneyCollect/.env.dev"
        )
    )
    EMAIL_HOST_USER = config(
        "EMAIL_USER"
    )  # Ваш email адрес (указан в переменных окружения .env.dev)
    EMAIL_HOST_PASSWORD = config(
        "EMAIL_PASSWORD"
    )  # Пароль от почтового ящика (указан в переменных окружения .env.dev)
    DEFAULT_FROM_EMAIL = config(
        "EMAIL_USER"
    )  # Адрес отправителя по умолчанию (указан в переменных окружения .env.dev

else:
    # Если проект развернут в Docker
    EMAIL_HOST_USER = conf(
        "EMAIL_USER"
    )  # Ваш email адрес (указан в переменных окружения .env.dev)
    EMAIL_HOST_PASSWORD = conf(
        "EMAIL_PASSWORD"
    )  # Пароль от почтового ящика (указан в переменных окружения .env.dev)
    DEFAULT_FROM_EMAIL = conf(
        "EMAIL_USER"
    )  # Адрес отправителя по умолчанию (указан в переменных окружения .env.dev)
    # print(EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL)

# Настройка шрифта, используемого утилитой graph_models
GRAPH_MODELS = {
    "all_applications": False,
    "group_models": True,
    "output": "png",
    "arrow_shape": "open",
    "fontname": "Roboto",  # Устанавливаем по умолчанию доступный в системе шрифта (исходный шрифт ROBOTO)
}
