# Generated by Django 5.2.1 on 2025-09-29 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название сбора"),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("birthday", "День рождения"),
                            ("wedding", "Свадьба"),
                            ("medical", "Медицинское лечение"),
                            ("charity", "Благотворительность"),
                            ("emergency", "Чрезвычайная ситуация"),
                            ("other", "Другое"),
                        ],
                        default="charity",
                        max_length=20,
                        verbose_name="Повод сбора",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание сбора")),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Целевая сумма",
                    ),
                ),
                (
                    "collected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Собранная сумма",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="Витрина сбора",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(verbose_name="Дата завершения сбора"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания сбора"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления сбора"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор сбора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Групповой сбор",
                "verbose_name_plural": "Групповые сборы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий к платежу"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время платежа"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Анонимный платеж"),
                ),
                (
                    "collect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.collect",
                        verbose_name="Сбор",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
            },
        ),
    ]
