# Generated by Django 5.2.1 on 2025-10-10 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="occasion",
            field=models.CharField(
                choices=[
                    ("birthday", "День рождения"),
                    ("wedding", "Свадьба"),
                    ("medical", "Лечение"),
                    ("charity", "Благотворительность"),
                    ("emergency", "Чрезвычайная ситуация"),
                    ("other", "Другое"),
                ],
                default="charity",
                max_length=20,
                verbose_name="Повод сбора",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Донатер",
            ),
        ),
    ]
