# Generated by Django 5.2.1 on 2025-10-12 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_collect_occasion_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 20, 6, 3, 40, 558472, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата завершения сбора",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="occasion",
            field=models.CharField(
                choices=[
                    ("birthday", "День рождения"),
                    ("wedding", "Свадьба"),
                    ("medical", "Лечение"),
                    ("charity", "Благотворительность"),
                    ("emergency", "Экстреная ситуация"),
                    ("other", "Другое"),
                ],
                default="charity",
                max_length=20,
                verbose_name="Повод сбора",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="target_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100000,
                max_digits=12,
                null=True,
                verbose_name="Целевая сумма",
            ),
        ),
    ]
