# Generated by Django 5.2.1 on 2025-10-12 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_collect_end_date_alter_collect_occasion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 20, 6, 19, 17, 379243, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата завершения сбора",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="occasion",
            field=models.CharField(
                choices=[
                    ("birthday", "День рождения"),
                    ("wedding", "Свадьба"),
                    ("medical", "Лечение"),
                    ("charity", "Благотворительность"),
                    ("emergency", "Экстреная ситуация"),
                    ("other", "Другое"),
                ],
                default="charity",
                max_length=40,
                verbose_name="Повод сбора",
            ),
        ),
    ]
