# Generated by Django 5.2.1 on 2025-10-13 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_collect_end_date_alter_collect_occasion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="collected_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Собранная сумма",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 21, 2, 57, 5, 80272, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата завершения сбора",
            ),
        ),
    ]
