# Generated by Django 5.2.1 on 2025-10-13 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_collect_collected_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2029, 12, 31, 0, 0),
                verbose_name="Дата завершения сбора",
            ),
        ),
    ]
